### ISSUE TITLE
add a bookmarkable route without category segment

### ISSUE THREAD

**Issue by jharting** [RedHatInsights/insights-advisor-frontend#187]
right now the URL route has the form of
https://access.redhat.com/insightsbeta/platform/advisor/actions/<category>/<rule_id>

If I want to link user to a rule page I may only know its rule_id but not its category. It would therefore be handy if this project also supported routes in form of:

https://access.redhat.com/insightsbeta/platform/advisor/actions/<rule_id>

**Comment by RonnyPfannschmidt** [comment]
A nice way might be to have a pseudo category called `+by_id` which in turn redirects to a normal url

**Comment by AllenBW** [comment]
for giggles, the jira ticket, https://projects.engineering.redhat.com/browse/RHCLOUD-394
