### ISSUE TITLE
Actions 2 table sorting broken

### ISSUE THREAD

**Issue by ryelo** [RedHatInsights/insights-advisor-frontend#194]
When sorting on the table, it doesn't correctly sort by ascending or descending. Some of the sorting doesn't work at all.

Example: Sorting by the Systems Exposed

**Comment by AllenBW** [comment]
Can confirm, looks like its been broken for a while, local sorting needs to be replace by api sorting though, which'll be a rewrite of whats there presently, so good catch, on the radar, *WILL FIX*

**Comment by bmclaughlin** [comment]
Fixed by https://github.com/RedHatInsights/insights-advisor-frontend/pull/204
