### ISSUE TITLE
Title on ListActions

### ISSUE THREAD

**Issue by ryelo** [RedHatInsights/insights-advisor-frontend#40]
What do you guys think about converting the `rule.description` to:
```jsx
<PageHeader>
    <PageHeaderTitle title={ this.state.rule.description }/>
</PageHeader>
```

![image](https://user-images.githubusercontent.com/12520842/45840889-3f948c80-bce6-11e8-9e19-62139537967b.png)

**Comment by AllenBW** [comment]
It does appear to align with current beta, so 👍 ovah here

**Comment by bmclaughlin** [comment]
I like it. :+1:
