### ISSUE TITLE
Bug: first rule in the rules table is not selectable

### ISSUE THREAD

**Issue by gkarat** [RedHatInsights/insights-advisor-frontend#850]
When you open the inventory details page (e.g., I used `https://cloud.redhat.com/insights/advisor/recommendations/network_device_unregister_issue|NETWORK_DEVICE_UNREGISTER_ISSUE/{INVENTORY_ID}`) and try to select the first item in the rules list, the UI does not react to your click, and the item remains unselected. For the rest of the items, it works OK (see the screenshot).

![image](https://user-images.githubusercontent.com/31385370/125828834-986132f3-af40-4455-9f14-54b5a35a2627.png)

**Comment by AllenBW** [comment]
not a bug, yah can't select rows that are disabled, if yah look real close the checkbox is disabled, for those rec we don't have playbooks for, yah can't remediate em, no point in having em select-able,

**Comment by gkarat** [comment]
gotcha!
