### ISSUE TITLE
Bug: Topics overflow the rule details component

### ISSUE THREAD

**Issue by gkarat** [RedHatInsights/insights-advisor-frontend#866]
"Topics related to the recommendation" can be really long. However, there is no wrapping that could limit the width of that block, and the components to the right side are just thrown away and not visible.

![Screenshot from 2021-08-24 10-19-14](https://user-images.githubusercontent.com/31385370/130582523-7eb3839d-32bb-4e25-8e05-674cf5747caf.png)

**Comment by leSamo** [comment]
Looks like this issue has been fixed in the 1 year since this ticket, the topics now wrap correctly, closing.
![Screenshot from 2022-09-20 23-10-03](https://user-images.githubusercontent.com/8426204/191365142-71ab9cd5-31fd-452c-a86e-029bac7c6178.png)
