### ISSUE TITLE
Bug: kebab is displayed for empty state message

### ISSUE THREAD

**Issue by gkarat** [RedHatInsights/insights-advisor-frontend#870]
If you have 0 affected systems for a single rec page, the empty message has an extra kebab.

![Screenshot from 2021-09-09 13-06-20](https://user-images.githubusercontent.com/31385370/132675236-13138d7f-836c-48cf-877e-7471e2f1799a.png)

**Comment by leSamo** [comment]
Looks like this issue has been fixed in the 1 year since this ticket, I verified all Advisor's tables, closing.
