### ISSUE TITLE
Bug: padding/margin issues in the Recs list page

### ISSUE THREAD

**Issue by gkarat** [RedHatInsights/insights-advisor-frontend#874]
There are a couple of issues on the recommendations list page caused by incorrect margins or padding params. See screenshots

![Screenshot from 2021-10-11 13-45-56](https://user-images.githubusercontent.com/31385370/136785027-d74d7c06-6b96-4cd5-b904-57bc0a0687f5.png)

![Screenshot from 2021-10-11 13-45-42](https://user-images.githubusercontent.com/31385370/136785034-30386c72-d6f5-4293-864e-3bbd0438d81b.png)

**Comment by leSamo** [comment]
Looks like this issue has been fixed in the 1 year since this ticket, closing.
